### ISSUE TITLE
trailing <br> not removed

### ISSUE THREAD

**Issue by dspjm** [ijgnd/anki21__remove_linebreaks__do_word_wrap#2]
Cannot remove <br> when editing in browser.

**Comment by ijgnd** [comment]
For me it works as expected in the browser.

I need more details

- Try with the latest Anki version 2.1.26. I don't care about older versions that I don't use
- just to be sure: It works as expected in the Add window?
- in the browser: Does the shortcut work?
- in the browser: What happens when you click on the icon?
- Disable all other add-ons and restart: Does the problem disappear?
- If it's only the shortcut that doesn't work in the browser it might be a shortcut conflict which means that another add-on also tries to use the same shortcut. Then the underlying components of Anki ignore the shortcut.

**Comment by dspjm** [comment]
I just try it again and it works. However, the problem is it cannot remove the trailing <br> at the end of the field. I remember it used to remove that one, so is it changed that it won't remove the trailing <br>?

**Comment by ijgnd** [comment]
> However, the problem is it cannot remove the trailing at the end of the field. I remember it used to remove that one, so is it changed that it won't remove the trailing ?

I don't have this problem with the code I process. Give some html source code where it doesn't work expected. I changed how this add-on works about a month ago which might explain why it works differently.

**Comment by dspjm** [comment]
> 
> 
> > However, the problem is it cannot remove the trailing at the end of the field. I remember it used to remove that one, so is it changed that it won't remove the trailing ?
> 
> I don't have this problem with the code I process. Give some html source code where it doesn't work expected. I changed how this add-on works about a month ago which might explain why it works differently.

Thanks. Try this "`The Goldilocks Rule<br>`" in the Front field.

**Comment by ijgnd** [comment]
I can confirm that the trailing "<br>" is not removed from a field with the content `The Goldilocks Rule<br>`

I haven't really looked into it but it doesn't seem like a quick fix. For me this trailing slash has no visual effect so I don't care about it at the moment. 

Does it have a visual effect for you? show screenshots.

**Comment by dspjm** [comment]
> Does it have a visual effect for you? show screenshots.

Well, it has an extra empty line between the questions and answers, and it may hide some notes I wrote in addition to looking wired. Because I basically copy from pdf, the trailing newline was always there, so I have to remove it by hand every time now. It would be great if this can be improved. Thanks.

**Comment by dspjm** [comment]
I am trying to work on the code myself, while I am not sure why line 56:

`.replace(/<br>/g, ' ')`

is not removing the trailing `<br>`?

**Comment by dspjm** [comment]
I think a fix can be
```
if (string.endsWith('<br>')))
string.slice(0, -4)
```
What do you think?

**Comment by ijgnd** [comment]
Thanks for looking into this. My js and html knowledge is very limited. So I have no idea why the regex you mentioned in your first post from today doesn't work. If the second post works that's great. I have no idea if there could be side effects etc.  I suggest you test it for a week or two. If you don't run into any problems I could upload it to ankiweb.

**Comment by ijgnd** [comment]
at least since Anki 2.1.41 from 2021-03-07 a trailing `<br>` seems to be removed by my add-on with the existing code, version from 2022-09.
