### ISSUE TITLE
Edition menu showing two icons 

### ISSUE THREAD

**Issue by succil3** [ijgnd/anki21__remove_linebreaks__do_word_wrap#3]
After last update, my edition's menu showing two icons 
![image](https://user-images.githubusercontent.com/82325112/114808953-aa63b280-9d7f-11eb-8669-17e3c040dc63.png)

**Comment by ijgnd** [comment]
Thanks for reporting this. I couldn't reproduce this and I never got another report about this. So I'm closing this. If you still have it let me know.
